name: New Release
on:
  push:
    branches:
      - main
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    name: Runs semantic release
    steps:
      - uses: actions/checkout@v3

      - uses: codfish/semantic-release-action@v3.1.0
        id: semantic
        with:
          dry-run: false
          branches: |
            ['main']
          additional-packages: |
            ['@semantic-release/git']
          plugins: |
            ['@semantic-release/git', '@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@semantic-release/git']
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: 000000000000000